### ISSUE TITLE
Xcode 11 and SPM not supported

### ISSUE THREAD

**Issue by JanRajtr** [appcompany/SwiftSky#12]
On Xcode 11 the following error causes fail with SPM:
```
Showing All Messages
: package at 'https://github.com/appcompany/SwiftSky' @ e7082626f60b089228cff836e5c118dcd81cc168 is using Swift tools version 3.1.0 which is no longer supported; consider using '// swift-tools-version:5.1' to specify the current tools version

```

**Comment by lucasilverentand** [comment]
Hi @JanRajtr,

I'm sorry but at the current time, I'm too pre-occupied with other projects. Somewhere next year I will have time to continue on my weather app which requires this repository.

Feel free to do a PR however!

**Comment by JanRajtr** [comment]
Hello, thank you for quick response. I created the pull request #13 
Cheers

**Comment by lucasilverentand** [comment]
It's merged thank you for your contribution!

**Comment by lucasilverentand** [comment]
@JanRajtr Just tested it using an empty Xcode project and it works

**Comment by JanRajtr** [comment]
Resolved now. :)
