### ISSUE TITLE
Add Alamofire dependency

### ISSUE THREAD

**Issue by tylerjvick** [appcompany/SwiftSky#3]
This is a great library, super easy to use!

I ran into one small issue when using SwiftSky with Carthage. There appears to be an undocumented Alamofire dependency that causes a crash when not found.

Manually adding Alamofire to my Cartfile fixed this, but perhaps there's a way to nest the Alamofire dependency within SwiftSky? I'm not sure if this can be accomplished (or if this is even a problem) with other dependency managers. Regardless, it would be great if this could be noted in the README.

Thanks!

**Comment by lucasilverentand** [comment]
I'll look into this asap. You're also allowed/encouraged to do a pull request ;). I'm busy on a project at the moment so I'll have the time somewhere next week.

Thanks for submitting an issue!

**Comment by lucasilverentand** [comment]
@tylerjvick Could you give me some logs or output?

**Comment by lucasilverentand** [comment]
I'm able to use Carthage successfully, therefor I'm closing this. Please let me know if you keep experiencing this problem.
