### ISSUE TITLE
Add InHg (Inch of mercury) as a PressureUnit

### ISSUE THREAD

**Issue by Jsayer7** [appcompany/SwiftSky#4]
Not an issue, but more of a feature request.

Inch of Mercury is a popular unit of pressure (iOS stock Weather app, WTForecast, Weather Underground) all have this unit of measure as the stock unit in their apps. It would be nice if this was available in the PressureUnit enum

**Comment by lucasilverentand** [comment]
This has been added in v 1.2.0
