### ISSUE TITLE
Temperatures always come back nil in Swift 4

### ISSUE THREAD

**Issue by ishabazz** [appcompany/SwiftSky#5]
For some reason  **json["temperature"]** always returns nil if cast to an optional Float in Swift 4.  Casting to an optional Double fixes this.

**Comment by lucasilverentand** [comment]
I'll make sure that will be solved before iOS 11 is released, hopefully beta 3.

**Comment by lucasilverentand** [comment]
@ishabazz could you confirm the issue is resolved with v1.3.0? Thanks for your contribution :)

**Comment by Jsayer7** [comment]
I can't seem to build the framework for use in Xcode 9 and Swift 4? I put 'github "AppCompany/SwiftSky" ~> 1.3' in the Cartfile and updated to no avail.

**Comment by lucasilverentand** [comment]
@Jsayer7 I'm trying to make some time to update SwiftSky and resolve all the bugs related to Swift 4 and Xcode 9.

**Comment by ishabazz** [comment]
Sorry. I missed the update. This is resolved for me. Thanks.

**Comment by lucasilverentand** [comment]
No problem! I'm closing this issue then
